<?php

namespace Unisys12\FakeCanine;

/**
 * FakeCanineBreed Generator
 *
 * Returns a random string representing a canine breed
 *
 * @author Phillip Jackson (unisys12) <unisys12@gmail.com>
 */
class FakeCanineBreedGenerator
{

    /**
     * breed()
     *
     * Return a random breed
     *
     * @return string
     */
    public function canineBreed()
    {
        $breed = array_rand($this->lists['breeds']);

        return $this->lists['breeds'][$breed];
    }

    private $lists = [
        'breeds' => [
            'Retriever (Labrador)',
            'German Shepherd',
            'Retriever (Golden)',
            'French Bulldog',
            'Bulldog',
            'Poodle',
            'Beagle',
            'Rottweiler',
            'Pointer (German Shorthaired)',
            'Pembroke Welsh Corgis',
            'Dachshund',
            'Yorkshire Terrier',
            'Australian Shepherd',
            'Boxer',
            'Siberian Huskie',
            'Cavalier King Charles Spaniel',
            'Great Dane',
            'Miniature Schnauzer',
            'Doberman Pinscher',
            'Shih Tzu',
            'Boston Terrier',
            'Havanese',
            'Bernese Mountain Dog',
            'Pomeranian',
            'Shetland Sheepdog',
            'Brittany',
            'Spaniel (English Springer)',
            'Spaniel (Cocker)',
            'Miniature American Shepherd',
            'Cane Corso',
            'Pug',
            'Mastiff',
            'Border Collie',
            'Vizsla',
            'Chihuahua',
            'Maltese',
            'Basset Hound',
            'Collie',
            'Weimaraner',
            'Newfoundland',
            'Belgian Malinoi',
            'Rhodesian Ridgeback',
            'Bichons Frise',
            'West Highland White Terrier',
            'Shiba Inu',
            'Retriever (Chesapeake Bay)',
            'Akita',
            'St. Bernard',
            'Portuguese Water Dog',
            'Spaniel (English Cocker)',
            'Bloodhound',
            'Bullmastiff',
            'Papillon',
            'Soft Coated Wheaten Terrier',
            'Australian Cattle Dog',
            'Scottish Terrier',
            'Whippet',
            'Samoyed',
            'Dalmatian',
            'Airedale Terrier',
            'Bull Terrier',
            'Wirehaired Pointing Griffon',
            'Pointer (German Wirehaired)',
            'Alaskan Malamute',
            'Chinese Shar-Pei',
            'Cardigan Welsh Corgi',
            'Italian Greyhound',
            'Dogues de Bordeaux',
            'Great Pyrenee',
            'Old English Sheepdog',
            'Giant Schnauzer',
            'Cairn Terrier',
            'Greater Swiss Mountain Dog',
            'Miniature Pinscher',
            'Russell Terrier',
            'Irish Wolfhound',
            'Chow Chow',
            'Lhasa Apsos',
            'Setter (Irish)',
            'Chinese Crested',
            'Coton de Tulear',
            'Staffordshire Bull Terrier',
            'Pekingese',
            'Border Terrier',
            'American Staffordshire Terrier',
            'Retriever (Nova Scotia Duck Tolling)',
            'Basenjis',
            'Keeshonden',
            'Spaniel (Boykin)',
            'Lagotti Romagnoli',
            'Rat Terrier',
            'Bouviers des Flandre',
            'Norwegian Elkhound',
            'Anatolian Shepherd',
            'Leonberger',
            'Brussels Griffon',
            'Standard Schnauzer',
            'Setter (English)',
            'Fox Terrier (Wire)',
            'Neapolitan Mastiff',
            'Tibetan Terrier',
            'Norwich Terrier',
            'Belgian Tervuren',
            'Retriever (Flat-Coated)',
            'Borzois',
            'Schipperkes',
            'Toy Fox Terrier',
            'Japanese Chin',
            'Silky Terrier',
            'Welsh Terrier',
            'Afghan Hound',
            'Miniature Bull Terrier',
            'Setter (Gordon)',
            'Black Russian Terrier',
            'Pointer',
            'Spinoni Italiani',
            'Tibetan Spaniel',
            'Parson Russell Terrier',
            'Irish Terrier',
            'American Eskimo Dog',
            'Beauceron',
            'Fox Terrier (Smooth)',
            'German Pinscher',
            'American Hairless Terrier',
            'Salukis',
            'Belgian Sheepdog',
            'Boerboel',
            'Tibetan Mastiff',
            'Treeing Walker Coonhound',
            'Spaniel (Welsh Springer)',
            'Norfolk Terrier',
            'Icelandic Sheepdog',
            'Kerry Blue Terrier',
            'Spaniel (Clumber)',
            'Briard',
            'Bearded Collie',
            'Xoloitzcuintli',
            'Bluetick Coonhound',
            'English Toy Spaniel',
            'Manchester Terrier',
            'Black and Tan Coonhound',
            'Australian Terrier',
            'Redbone Coonhound',
            'Spanish Water Dog',
            'Wirehaired Vizsla',
            'Berger Picard',
            'Portuguese Podengo Pequeno',
            'Lakeland Terrier',
            'Scottish Deerhound',
            'Affenpinscher',
            'Bedlington Terrier',
            'Petits Bassets Griffons Vendeen',
            'Spaniel (Field)',
            'Sealyham Terrier',
            'Setter (Irish Red and White)',
            'Pumik',
            'Nederlandse Kooikerhondje',
            'Lowchen',
            'Swedish Vallhund',
            'Pulik',
            'Pharaoh Hound',
            'Greyhound',
            'Retriever (Curly-Coated)',
            'Spaniel (American Water)',
            'Finnish Lapphund',
            'Kuvaszok',
            'Entlebucher Mountain Dog',
            'Glen of Imaal Terrier',
            'Norwegian Buhund',
            'Spaniel (Irish Water)',
            'Ibizan Hound',
            'Otterhound',
            'Polish Lowland Sheepdog',
            'Dandie Dinmont Terrier',
            'American English Coonhound',
            'Spaniel (Sussex)',
            'Plott Hound',
            'Grand Basset Griffon Vendeen',
            'Canaan Dog',
            'Bergamasco Sheepdog',
            'Komondorok',
            'Pyrenean Shepherd',
            'Finnish Spitz',
            'Chinook',
            'Cirnechi dell’Etna',
            'Harrier',
            'Skye Terrier',
            'Cesky Terrier',
            'American Foxhound',
            'Azawakh',
            'Sloughis',
            'Norwegian Lundehund',
            'English Foxhound'
        ],
    ];
}
